import * as React from 'react';
import { useDemoData } from '@mui/x-data-grid-generator';
import {
  DataGridPro,
  GridApiRef,
  GridCsvExportOptions,
  gridRowTreeSelector,
  GridToolbarContainer,
  gridVisibleSortedRowIdsSelector,
  useGridApiContext,
  useGridRootProps,
} from '@mui/x-data-grid-pro';

const getRowsWithGroups = (apiRef: GridApiRef) =>
  gridVisibleSortedRowIdsSelector(apiRef.current.state);

const getRowsWithoutGroups = (apiRef: GridApiRef) => {
  const rows = gridVisibleSortedRowIdsSelector(apiRef.current.state);
  const tree = gridRowTreeSelector(apiRef.current.state);

  return rows.filter((rowId) => !tree[rowId].isAutoGenerated);
};

const CustomToolbar = () => {
  const rootProps = useGridRootProps();
  const apiRef = useGridApiContext();

  const handleExport = (options: GridCsvExportOptions) =>
    apiRef.current.exportDataAsCsv(options);

  const buttonBaseProps = {
    color: 'primary',
    size: 'small',
    startIcon: <rootProps.components.ExportIcon />,
    ...rootProps.componentsProps?.baseButton,
  };

  return (
    <GridToolbarContainer>
      <rootProps.components.BaseButton
        {...buttonBaseProps}
        onClick={() => handleExport({ getRowsToExport: getRowsWithGroups })}
      >
        Rows with groups
      </rootProps.components.BaseButton>
      <rootProps.components.BaseButton
        {...buttonBaseProps}
        onClick={() => handleExport({ getRowsToExport: getRowsWithoutGroups })}
      >
        Rows without groups
      </rootProps.components.BaseButton>
    </GridToolbarContainer>
  );
};

export default function CsvGetRowsToExport() {
  const { data, loading } = useDemoData({
    dataSet: 'Commodity',
    rowLength: 100,
    maxColumns: 6,
  });

  return (
    <div style={{ height: 300, width: '100%' }}>
      <DataGridPro
        {...data}
        loading={loading}
        components={{ Toolbar: CustomToolbar }}
        initialState={{
          rowGrouping: {
            model: ['commodity'],
          },
        }}
        experimentalFeatures={{ rowGrouping: true }}
        defaultGroupingExpansionDepth={-1}
      />
    </div>
  );
}
