import { CSSObject, Theme } from '@mui/material/styles';
import {
  red,
  pink,
  indigo,
  blue,
  teal,
  green,
  lime,
  amber,
  deepOrange,
  orange,
  grey,
  purple,
} from '@mui/material/colors';

/**
 * Custom color mappings for scheduler events.
 * These are derived from Material UI color palettes but with custom selections
 * for optimal visual appearance in both light and dark modes.
 */
const eventColorTokens = {
  red: {
    light: {
      main: red[500],
      'surface-bold': red[200],
      'surface-bold-hover': '#ED8D8D',
      'on-surface-bold': '#760F0F',
      'surface-bold-selected': '#FF5959',
      'surface-bold-selected-hover': red[400],
      'on-surface-bold-selected': '#FFFFFF',
      'surface-subtle': red[50],
      'surface-subtle-hover': '#FEDCDF',
      'surface-accent': red[900],
      'on-surface-subtle-primary': '#760F0F',
      'on-surface-subtle-secondary': red[900],
    },
    dark: {
      main: red[600],
      'surface-bold': '#821b1b',
      'surface-bold-hover': '#A02424',
      'on-surface-bold': '#FFFFFF',
      'surface-bold-selected': red[700],
      'surface-bold-selected-hover': red[800],
      'on-surface-bold-selected': '#FFFFFF',
      'surface-subtle': '#330909',
      'surface-subtle-hover': '#450C0C',
      'surface-accent': red[300],
      'on-surface-subtle-primary': red[100],
      'on-surface-subtle-secondary': red[300],
    },
  },
  pink: {
    light: {
      main: pink[400],
      'surface-bold': '#fca4c1',
      'surface-bold-hover': pink[200],
      'on-surface-bold': pink[900],
      'surface-bold-selected': '#FC4B87',
      'surface-bold-selected-hover': pink[400],
      'on-surface-bold-selected': pink[900],
      'surface-subtle': pink[50],
      'surface-subtle-hover': '#FACCDC',
      'surface-accent': pink[800],
      'on-surface-subtle-primary': pink[900],
      'on-surface-subtle-secondary': pink[800],
    },
    dark: {
      main: pink[600],
      'surface-bold': '#67103E',
      'surface-bold-hover': '#73234D',
      'on-surface-bold': '#FFFFFF',
      'surface-bold-selected': pink[700],
      'surface-bold-selected-hover': pink[800],
      'on-surface-bold-selected': '#FFFFFF',
      'surface-subtle': '#43132d',
      'surface-subtle-hover': '#4F1735',
      'surface-accent': pink[300],
      'on-surface-subtle-primary': pink[50],
      'on-surface-subtle-secondary': pink[200],
    },
  },
  purple: {
    light: {
      main: purple[400],
      'surface-bold': '#D6ABDD',
      'surface-bold-hover': purple[200],
      'on-surface-bold': '#380673',
      'surface-bold-selected': purple[300],
      'surface-bold-selected-hover': purple[400],
      'on-surface-bold-selected': '#FFFFFF',
      'surface-subtle': purple[50],
      'surface-subtle-hover': '#EDD0F1',
      'surface-accent': purple[800],
      'on-surface-subtle-primary': '#380673',
      'on-surface-subtle-secondary': purple[800],
    },
    dark: {
      main: purple[700],
      'surface-bold': '#5A0C70',
      'surface-bold-hover': '#751690',
      'on-surface-bold': '#FFFFFF',
      'surface-bold-selected': purple[700],
      'surface-bold-selected-hover': purple[800],
      'on-surface-bold-selected': '#FFFFFF',
      'surface-subtle': '#2c153a',
      'surface-subtle-hover': '#361A47',
      'surface-accent': purple[300],
      'on-surface-subtle-primary': purple[50],
      'on-surface-subtle-secondary': purple[200],
    },
  },
  indigo: {
    light: {
      main: indigo[500],
      'surface-bold': indigo[200],
      'surface-bold-hover': '#8694E2',
      'on-surface-bold': indigo[900],
      'surface-bold-selected': indigo[400],
      'surface-bold-selected-hover': indigo[500],
      'on-surface-bold-selected': indigo[900],
      'surface-subtle': indigo[50],
      'surface-subtle-hover': '#D3D6EE',
      'surface-accent': indigo[700],
      'on-surface-subtle-primary': indigo[900],
      'on-surface-subtle-secondary': indigo[700],
    },
    dark: {
      main: indigo[600],
      'surface-bold': '#19205E',
      'surface-bold-hover': '#2B316B',
      'on-surface-bold': '#FFFFFF',
      'surface-bold-selected': indigo[600],
      'surface-bold-selected-hover': '#4957B2',
      'on-surface-bold-selected': '#FFFFFF',
      'surface-subtle': '#13163c',
      'surface-subtle-hover': '#191d49',
      'surface-accent': indigo[300],
      'on-surface-subtle-primary': indigo[50],
      'on-surface-subtle-secondary': indigo[200],
    },
  },
  blue: {
    light: {
      main: blue[600],
      'surface-bold': blue[200],
      'surface-bold-hover': '#5EB5FC',
      'on-surface-bold': '#0B3A84',
      'surface-bold-selected': blue[400],
      'surface-bold-selected-hover': blue[500],
      'on-surface-bold-selected': '#FFFFFF',
      'surface-subtle': blue[50],
      'surface-subtle-hover': '#CAE5FC',
      'surface-accent': blue[800],
      'on-surface-subtle-primary': '#0B3A84',
      'on-surface-subtle-secondary': blue[800],
    },
    dark: {
      main: blue[600],
      'surface-bold': '#00347c',
      'surface-bold-hover': '#043668',
      'on-surface-bold': '#FFFFFF',
      'surface-bold-selected': blue[700],
      'surface-bold-selected-hover': blue[800],
      'on-surface-bold-selected': '#FFFFFF',
      'surface-subtle': '#002040',
      'surface-subtle-hover': '#032547',
      'surface-accent': blue[300],
      'on-surface-subtle-primary': blue[50],
      'on-surface-subtle-secondary': blue[200],
    },
  },
  teal: {
    light: {
      main: teal[600],
      'surface-bold': teal[200],
      'surface-bold-hover': '#3DBEB2',
      'on-surface-bold': teal[900],
      'surface-bold-selected': teal[400],
      'surface-bold-selected-hover': teal[500],
      'on-surface-bold-selected': '#FFFFFF',
      'surface-subtle': teal[50],
      'surface-subtle-hover': '#C9E9E6',
      'surface-accent': teal[800],
      'on-surface-subtle-primary': teal[900],
      'on-surface-subtle-secondary': teal[800],
    },
    dark: {
      main: teal[700],
      'surface-bold': '#044036',
      'surface-bold-hover': '#034539',
      'on-surface-bold': '#FFFFFF',
      'surface-bold-selected': teal[700],
      'surface-bold-selected-hover': teal[800],
      'on-surface-bold-selected': '#FFFFFF',
      'surface-subtle': '#023028',
      'surface-subtle-hover': '#03342c',
      'surface-accent': teal[300],
      'on-surface-subtle-primary': teal[50],
      'on-surface-subtle-secondary': teal[200],
    },
  },
  green: {
    light: {
      main: green[600],
      'surface-bold': green[200],
      'surface-bold-hover': '#80CF83',
      'on-surface-bold': '#164B1A',
      'surface-bold-selected': green[500],
      'surface-bold-selected-hover': green[600],
      'on-surface-bold-selected': '#FFFFFF',
      'surface-subtle': green[50],
      'surface-subtle-hover': '#D5ECD6',
      'surface-accent': green[800],
      'on-surface-subtle-primary': '#164B1A',
      'on-surface-subtle-secondary': green[800],
    },
    dark: {
      main: green[700],
      'surface-bold': '#0F3D13',
      'surface-bold-hover': '#133515',
      'on-surface-bold': '#FFFFFF',
      'surface-bold-selected': green[800],
      'surface-bold-selected-hover': green[900],
      'on-surface-bold-selected': '#FFFFFF',
      'surface-subtle': '#0e2810',
      'surface-subtle-hover': '#0D3010',
      'surface-accent': green[300],
      'on-surface-subtle-primary': green[50],
      'on-surface-subtle-secondary': green[200],
    },
  },
  lime: {
    light: {
      main: lime[700],
      'surface-bold': '#D0DF86',
      'surface-bold-hover': '#CAE059',
      'on-surface-bold': '#524b07',
      'surface-bold-selected': '#959B1F',
      'surface-bold-selected-hover': '#898F1D',
      'on-surface-bold-selected': '#FFFFFF',
      'surface-subtle': lime[50],
      'surface-subtle-hover': '#F3F6D0',
      'surface-accent': lime[900],
      'on-surface-subtle-primary': '#625A0D',
      'on-surface-subtle-secondary': lime[900],
    },
    dark: {
      main: lime[800],
      'surface-bold': '#50490A',
      'surface-bold-hover': '#5E571D',
      'on-surface-bold': '#FFFFFF',
      'surface-bold-selected': lime[900],
      'surface-bold-selected-hover': '#706510',
      'on-surface-bold-selected': '#FFFFFF',
      'surface-subtle': '#3c380d',
      'surface-subtle-hover': '#433F0F',
      'surface-accent': lime[300],
      'on-surface-subtle-primary': lime[50],
      'on-surface-subtle-secondary': lime[200],
    },
  },
  amber: {
    light: {
      main: '#FFB840',
      // 'surface-bold': amber[800],
      'surface-bold': amber[200],
      'surface-bold-hover': '#FFD75C',
      'on-surface-bold': '#6c4600',
      'surface-bold-selected': amber[800],
      'surface-bold-selected-hover': '#E98300',
      'on-surface-bold-selected': '#FFFFFF',
      'surface-subtle': '#FFF2CC',
      'surface-subtle-hover': '#FFECB2',
      'surface-accent': '#B68800',
      'on-surface-subtle-primary': '#6c4600',
      'on-surface-subtle-secondary': '#AA7F00',
    },
    dark: {
      main: '#FFB840',
      'surface-bold': '#8e5c00',
      'surface-bold-hover': '#9C6501',
      'on-surface-bold': '#FFFFFF',
      'surface-bold-selected': amber[700],
      'surface-bold-selected-hover': '#D58600',
      'on-surface-bold-selected': '#FFFFFF',
      'surface-subtle': '#3d2504',
      'surface-subtle-hover': '#4D2E05',
      'surface-accent': amber[300],
      'on-surface-subtle-primary': amber[50],
      'on-surface-subtle-secondary': amber[100],
    },
  },
  orange: {
    light: {
      main: deepOrange[400],
      'surface-bold': '#ffb77c',
      'surface-bold-hover': '#FFA55C',
      'on-surface-bold': '#A73B00',
      'surface-bold-selected': deepOrange[400],
      'surface-bold-selected-hover': deepOrange[500],
      'surface-subtle': '#ffe3cc',
      'surface-subtle-hover': '#FFD5B2',
      'surface-accent': orange[900],
      'on-surface-subtle-primary': '#A73B00',
      'on-surface-subtle-secondary': orange[900],
    },
    dark: {
      main: deepOrange[700],
      'surface-bold': '#6D2510',
      'surface-bold-hover': '#7D351F',
      'on-surface-bold': '#FFFFFF',
      'surface-bold-selected': orange[900],
      'surface-bold-selected-hover': '#E85F14',
      'on-surface-bold-selected': '#FFFFFF',
      'surface-subtle': '#4b1a0b',
      'surface-subtle-hover': '#7D351F',
      'surface-accent': orange[300],
      'on-surface-subtle-primary': orange[50],
      'on-surface-subtle-secondary': orange[100],
    },
  },
  grey: {
    light: {
      main: grey[400],
      'surface-bold': grey[400],
      'surface-bold-hover': grey[500],
      'on-surface-bold': grey[900],
      'surface-bold-selected': grey[600],
      'surface-bold-selected-hover': grey[700],
      'on-surface-bold-selected': '#FFFFFF',
      'surface-subtle': grey[100],
      'surface-subtle-hover': grey[200],
      'surface-accent': grey[800],
      'on-surface-subtle-primary': grey[900],
      'on-surface-subtle-secondary': grey[800],
    },
    dark: {
      main: grey[600],
      'surface-bold': grey[800],
      'surface-bold-hover': '#4f4f4f',
      'on-surface-bold': '#FFFFFF',
      'surface-bold-selected': grey[700],
      'surface-bold-selected-hover': grey[800],
      'on-surface-bold-selected': '#FFFFFF',
      'surface-subtle': '#1d1d1d',
      'surface-subtle-hover': grey[900],
      'surface-accent': grey[400],
      'on-surface-subtle-primary': grey[50],
      'on-surface-subtle-secondary': grey[400],
    },
  },
} as const;

export type PaletteName = keyof typeof eventColorTokens;

/**
 * Generates palette variants for MUI styled components.
 * Use with styled components: `variants: getPaletteVariants(theme)`
 */
export const getPaletteVariants = (theme: Theme) => {
  return Object.entries(eventColorTokens).map(([colorName, colorValues]) => ({
    props: { palette: colorName as PaletteName },
    style: {
      '--event-main': colorValues.light.main,
      '--event-surface-bold': colorValues.light['surface-bold'],
      '--event-on-surface-bold': colorValues.light['on-surface-bold'],
      '--event-surface-bold-hover':
        colorValues.light['surface-bold-hover'] ||
        'color-mix(in srgb, var(--event-surface-bold), black 4%);',
      '--event-surface-subtle': colorValues.light['surface-subtle'],
      '--event-surface-subtle-hover': colorValues.light['surface-subtle-hover'],
      '--event-surface-accent': colorValues.light['surface-accent'],
      '--event-on-surface-subtle-primary': colorValues.light['on-surface-subtle-primary'],
      '--event-on-surface-subtle-secondary': colorValues.light['on-surface-subtle-secondary'],
      ...theme.applyStyles('dark', {
        '--event-main': colorValues.dark.main,
        '--event-surface-bold': colorValues.dark['surface-bold'],
        '--event-on-surface-bold': colorValues.dark['on-surface-bold'],
        '--event-surface-bold-hover': colorValues.dark['surface-bold-hover'],
        '--event-surface-subtle': colorValues.dark['surface-subtle'],
        '--event-surface-subtle-hover': colorValues.dark['surface-subtle-hover'],
        '--event-surface-accent': colorValues.dark['surface-accent'],
        '--event-on-surface-subtle-primary': colorValues.dark['on-surface-subtle-primary'],
        '--event-on-surface-subtle-secondary': colorValues.dark['on-surface-subtle-secondary'],
      }),
    } as CSSObject,
  }));
};

/**
 * CSS variable tokens for the scheduler.
 * These are applied to root components (EventCalendar, standalone views).
 */
export const schedulerTokens: CSSObject = {
  // Gray scale (using MUI grey)
  '--gray-1': grey[50],
  '--gray-2': grey[100],
  '--gray-3': grey[200],
  '--gray-4': grey[300],
  '--gray-5': grey[400],
  '--gray-6': grey[500],
  '--gray-7': grey[600],
  '--gray-8': grey[700],
  '--gray-9': grey[800],
  '--gray-10': grey[900],

  // Semantic aliases
  '--border-color': grey[200],
  '--weekend-background': grey[100],
  '--surface': 'white',
};
