coverage:
  ignore:
    - 'packages/x-charts-vendor'
    - '**/*.test.tsx'
  status:
    project:
      default:
        target: auto
        threshold: 1%
      adapters:
        target: 100%
        paths:
          - 'packages/x-date-pickers/src/AdapterDateFns/AdapterDateFns.ts'
          - 'packages/x-date-pickers/src/AdapterDateFnsV3/AdapterDateFnsV3.ts'
          - 'packages/x-date-pickers/src/AdapterDateFnsJalali/AdapterDateFnsJalali.ts'
          - 'packages/x-date-pickers/src/AdapterDateFnsJalaliV3/AdapterDateFnsJalaliV3.ts'
          - 'packages/x-date-pickers/src/AdapterDayjs/AdapterDayjs.ts'
          - 'packages/x-date-pickers/src/AdapterLuxon/AdapterLuxon.ts'
          - 'packages/x-date-pickers/src/AdapterMoment/AdapterMoment.ts'
          - 'packages/x-date-pickers/src/AdapterMomentHijri/AdapterMomentHijri.ts'
          - 'packages/x-date-pickers/src/AdapterMomentJalaali/AdapterMomentJalaali.ts'
    patch: off

comment: false
