coverage:
  ignore:
    - 'packages/x-charts-vendor'
    - '**/*.test.tsx'
    - '**/*.test.ts'
  status:
    project:
      default:
        target: auto
        threshold: 1%
      adapters:
        target: 100%
        paths:
          - packages/x-date-pickers/src/Adapter*/Adapter*.ts
    patch: off

comment: false
