packages:
  - packages/*
  - docs
  - test
  - test/*
  - bundle-size
ignoredBuiltDependencies:
  - '@mui/monorepo'
  - msw
onlyBuiltDependencies:
  - '@swc/core'
  - '@vvago/vale'
  - 'core-js'
  - 'esbuild'
  - 'nx'
  - 'sharp'
catalog:
  '@babel/core': ^7.27.4
  '@babel/plugin-transform-react-constant-elements': ^7.27.1
  '@babel/plugin-transform-runtime': ^7.27.4
  '@babel/preset-typescript': ^7.27.1
  '@babel/runtime': ^7.27.6
  '@babel/traverse': ^7.27.4
  '@emotion/cache': ^11.14.0
  '@emotion/react': ^11.14.0
  '@emotion/styled': ^11.14.0
  '@mui/icons-material': ^7.1.1
  '@mui/internal-test-utils': ^2.0.9
  '@mui/material': ^7.1.1
  '@mui/stylis-plugin-rtl': ^7.1.0
  '@mui/system': ^7.1.1
  '@mui/utils': ^7.1.1
  '@playwright/test': ^1.53.0
  '@react-spring/web': ^10.0.1
  '@types/chance': ^1.1.6
  '@types/d3-scale': ^4.0.9
  '@types/format-util': ^1.0.4
  '@types/karma': ^6.3.9
  '@types/lodash': ^4.17.17
  '@types/luxon': ^3.6.2
  '@types/moment-hijri': ^2.1.4
  '@types/moment-jalaali': ^0.7.9
  '@types/prop-types': ^15.7.15
  '@types/react': 19.0.12
  '@types/react-dom': 19.0.4
  '@types/react-router': ^5.1.20
  '@types/react-transition-group': ^4.4.12
  '@types/semver': ^7.7.0
  '@types/use-sync-external-store': ^1.5.0
  '@typescript-eslint/parser': ^8.34.1
  autoprefixer: ^10.4.21
  babel-plugin-module-resolver: ^5.0.2
  babel-plugin-optimize-clsx: ^2.6.2
  babel-plugin-react-remove-properties: ^0.3.0
  babel-plugin-transform-react-remove-prop-types: ^0.4.24
  chance: ^1.1.13
  clsx: ^2.1.1
  cross-env: ^7.0.3
  csstype: ^3.1.3
  date-fns: ^4.1.0
  date-fns-jalali: ^4.1.0-0
  dayjs: ^1.11.13
  exceljs: ^4.4.0
  fast-glob: ^3.3.3
  jscodeshift: 17.3.0
  lodash: ^4.17.21
  luxon: ^3.6.1
  moment: ^2.30.1
  moment-hijri: ^3.0.0
  moment-jalaali: ^0.10.4
  moment-timezone: ^0.6.0
  prop-types: ^15.8.1
  react: 19.0.0
  react-dom: 19.0.0
  react-router: ^7.6.2
  react-transition-group: ^4.4.5
  reselect: ^5.1.1
  rimraf: ^6.0.1
  serve: ^14.2.4
  stylis: ^4.3.6
  tsx: ^4.20.3
  use-sync-external-store: ^1.5.0
  vitest: 3.2.4
  '@vitejs/plugin-react': ^4.6.0
  '@vitejs/plugin-react-swc': ^3.10.2
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/browser': ^3.2.4
  '@vitest/ui': ^3.2.4
  webpack-bundle-analyzer: ^4.10.2
  yargs: ^18.0.0
