"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.renderCountry = renderCountry;
var React = require("react");
var Box_1 = require("@mui/material/Box");
var x_data_grid_premium_1 = require("@mui/x-data-grid-premium");
var useStaticFlag = typeof DISABLE_CHANCE_RANDOM !== 'undefined' && DISABLE_CHANCE_RANDOM;
var laosFlag = "\n<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 900 600\">\n  <path fill=\"#ce1126\" d=\"M0 0h900v600H0z\" />\n  <path fill=\"#002868\" d=\"M0 150h900v300H0z\" />\n  <circle r=\"120\" cy=\"300\" cx=\"450\" fill=\"#fff\" />\n</svg>\n";
var staticFlagURI = "data:image/svg+xml;charset=UTF-8,".concat(encodeURIComponent(laosFlag));
var Country = React.memo(function Country(props) {
    var value = props.value;
    return (<Box_1.default sx={{
            width: '100%',
            display: 'flex',
            alignItems: 'center',
            '&  > img': {
                mr: 0.5,
                flexShrink: 0,
                width: '20px',
            },
        }}>
      <img loading="lazy" width="20" src={useStaticFlag ? staticFlagURI : "https://flagcdn.com/w20/".concat(value.code.toLowerCase(), ".png")} srcSet={useStaticFlag ? undefined : "https://flagcdn.com/w40/".concat(value.code.toLowerCase(), ".png 2x")} alt=""/>

      <Box_1.default component="span" sx={{ overflow: 'hidden', textOverflow: 'ellipsis' }}>
        {value.label}
      </Box_1.default>
    </Box_1.default>);
});
function renderCountry(params) {
    if (params.value == null) {
        return '';
    }
    if (params.aggregation || (0, x_data_grid_premium_1.isAutogeneratedRow)(params.row)) {
        return params.value;
    }
    return <Country value={params.value}/>;
}
