import {
  GridRowId,
  GridRowTreeConfig,
  GridTreeNode,
  GridFilterState,
  GridFilterModel,
  GridServerSideGroupNode,
  GridRowIdToModelLookup,
  GridValidRowModel,
} from '@mui/x-data-grid';
import {
  GridAggregatedFilterItemApplier,
  GridApiCommunity,
  passFilterLogic,
} from '@mui/x-data-grid/internals';
import { DataGridProProcessedProps } from '../../../models/dataGridProProps';

interface FilterRowTreeFromTreeDataParams {
  rowTree: GridRowTreeConfig;
  disableChildrenFiltering: boolean;
  isRowMatchingFilters: GridAggregatedFilterItemApplier | null;
  filterModel: GridFilterModel;
  apiRef: React.MutableRefObject<GridApiCommunity>;
}

export const TREE_DATA_STRATEGY = 'tree-data';
export const TREE_DATA_LAZY_LOADING_STRATEGY = 'tree-data-lazy-loading';

/**
 * A node is visible if one of the following criteria is met:
 * - One of its children is passing the filter
 * - It is passing the filter
 */
export const filterRowTreeFromTreeData = (
  params: FilterRowTreeFromTreeDataParams,
): Omit<GridFilterState, 'filterModel'> => {
  const { rowTree, disableChildrenFiltering, isRowMatchingFilters } = params;
  const visibleRowsLookup: Record<GridRowId, boolean> = {};
  const filteredRowsLookup: Record<GridRowId, boolean> = {};
  const filteredDescendantCountLookup: Record<GridRowId, number> = {};

  const filterTreeNode = (
    node: GridTreeNode,
    isParentMatchingFilters: boolean,
    areAncestorsExpanded: boolean,
  ): number => {
    const shouldSkipFilters = disableChildrenFiltering && node.depth > 0;

    let isMatchingFilters: boolean | null;
    if (shouldSkipFilters) {
      isMatchingFilters = null;
    } else if (!isRowMatchingFilters || node.type === 'footer') {
      isMatchingFilters = true;
    } else {
      const { passingFilterItems, passingQuickFilterValues } = isRowMatchingFilters(node.id);
      isMatchingFilters = passFilterLogic(
        [passingFilterItems],
        [passingQuickFilterValues],
        params.filterModel,
        params.apiRef,
      );
    }

    let filteredDescendantCount = 0;
    if (node.type === 'group') {
      node.children.forEach((childId) => {
        const childNode = rowTree[childId];
        const childSubTreeSize = filterTreeNode(
          childNode,
          isMatchingFilters ?? isParentMatchingFilters,
          areAncestorsExpanded && !!node.childrenExpanded,
        );

        filteredDescendantCount += childSubTreeSize;
      });
    }

    let shouldPassFilters: boolean;
    switch (isMatchingFilters) {
      case true: {
        shouldPassFilters = true;
        break;
      }
      case false: {
        shouldPassFilters = filteredDescendantCount > 0;
        break;
      }
      default: {
        shouldPassFilters = isParentMatchingFilters;
        break;
      }
    }

    visibleRowsLookup[node.id] = shouldPassFilters && areAncestorsExpanded;
    filteredRowsLookup[node.id] = shouldPassFilters;

    // TODO: Should we keep storing the visibility status of footer independently or rely on the group visibility in the selector ?
    if (node.type === 'group' && node.footerId != null) {
      visibleRowsLookup[node.footerId] =
        shouldPassFilters && areAncestorsExpanded && !!node.childrenExpanded;
    }

    if (!shouldPassFilters) {
      return 0;
    }

    filteredDescendantCountLookup[node.id] = filteredDescendantCount;

    if (node.type === 'footer') {
      return filteredDescendantCount;
    }

    return filteredDescendantCount + 1;
  };

  const nodes = Object.values(rowTree);
  for (let i = 0; i < nodes.length; i += 1) {
    const node = nodes[i];
    if (node.depth === 0) {
      filterTreeNode(node, true, true);
    }
  }

  return {
    visibleRowsLookup,
    filteredRowsLookup,
    filteredDescendantCountLookup,
  };
};

export const iterateTreeNodes = (
  dataRowIdToModelLookup: GridRowIdToModelLookup<GridValidRowModel>,
  tree: GridRowTreeConfig,
  nodeId: GridTreeNode['id'],
  isServerSideRow: DataGridProProcessedProps['isServerSideRow'],
) => {
  const node = tree[nodeId];

  if (node.type === 'leaf') {
    const row = dataRowIdToModelLookup[node.id];
    if (!row) {
      return;
    }
    if (row && isServerSideRow!(row)) {
      const groupingField = '__no_field__';
      const groupingKey = node.groupingKey ?? '__no_key__';
      const updatedNode: GridServerSideGroupNode = {
        ...node,
        type: 'group',
        children: [],
        childrenFromPath: {},
        isAutoGenerated: false,
        groupingField,
        groupingKey,
        isServerSide: true,
        isLoading: false,
        childrenFetched: false,
      };
      tree[node.id] = updatedNode;
    }
    return;
  }

  if (node.type === 'group') {
    for (let i = 0; i < node.children.length; i += 1) {
      iterateTreeNodes(dataRowIdToModelLookup, tree, node.children[i], isServerSideRow);
    }
  }
};
