import type { Pipeline } from '../../core/pipeline';

export type GridRowId = string | number;

export interface GridRowModel {
  id?: GridRowId;
  [key: string]: any;
}

export type GridRowModelUpdate<TRow> = Partial<TRow> & {
  _action?: 'delete';
};

export interface GridLeafNode {
  id: GridRowId;
  type: 'leaf';
  depth: number;
  parent: GridRowId;
  groupingKey: string | null;
}

export interface GridGroupNode {
  id: GridRowId;
  type: 'group';
  depth: number;
  parent: GridRowId | null;
  groupingKey: string | null;
  groupingField: string | null;
  children: GridRowId[];
  childrenFromPath: Record<string, GridRowId>;
  childrenExpanded: boolean;
  isAutoGenerated: boolean;
  footerId?: GridRowId;
}

export type GridTreeNode = GridLeafNode | GridGroupNode;

export type GridRowTreeConfig = Record<GridRowId, GridTreeNode>;

export type GridRowIdToModelLookup<R extends GridRowModel = GridRowModel> = Record<GridRowId, R>;

export interface RowsState {
  dataRowIds: GridRowId[];
  dataRowIdToModelLookup: GridRowIdToModelLookup;
  tree: GridRowTreeConfig;
  treeDepths: Record<number, number>;
  totalRowCount: number;
  totalTopLevelRowCount: number;
  loading: boolean;
  groupingName: string;
  processedRowIds: GridRowId[];
}

export interface RowsOptions<TRow> {
  rows: TRow[];
  getRowId?: (row: TRow) => GridRowId;
  loading?: boolean;
  /**
   * The total number of rows. Set to -1 for unknown row count.
   * Used in external pagination mode.
   */
  rowCount?: number;
}

export interface RowIdsPipelineProcessor {
  /**
   * Transform the row IDs. Receives the output of the previous processor
   * (or raw dataRowIds for the first processor).
   */
  (inputIds: GridRowId[]): GridRowId[];
}

export interface RowsPluginState {
  rows: RowsState;
}

export interface RowsPluginOptions<TRow = any> extends RowsOptions<TRow> {
  initialState?: {
    rows?: Partial<RowsState>;
  };
}

export interface RowsApi<TRow = any> {
  getRow: (id: GridRowId) => TRow | null;
  getRowId: (row: TRow) => GridRowId;
  getRowModels: () => Map<GridRowId, TRow>;
  getRowsCount: () => number;
  getAllRowIds: () => GridRowId[];
  setRows: (rows: TRow[]) => void;
  updateRows: (updates: GridRowModelUpdate<TRow>[]) => void;
  getRowNode: (id: GridRowId) => GridTreeNode | null;
  setLoading: (loading: boolean) => void;
  rowIdsPipeline: Pipeline<GridRowId[]>;
}

export interface RowsPluginApi<TRow = any> {
  rows: RowsApi<TRow>;
}
