/* eslint-disable no-restricted-imports */
// @ts-nocheck
import {
  CalendarPicker,
  CalendarPickerProps,
  CalendarPickerSlotsComponent,
  CalendarPickerSlotsComponentsProps,
  CalendarPickerClasses,
  CalendarPickerClassKey,
  calendarPickerClasses,
  getCalendarPickerUtilityClass,
  MonthPicker,
  MonthPickerProps,
  MonthPickerClasses,
  MonthPickerClassKey,
  monthPickerClasses,
  getMonthPickerUtilityClass,
  YearPicker,
  YearPickerProps,
  YearPickerClasses,
  YearPickerClassKey,
  yearPickerClasses,
  getYearPickerUtilityClass,
  ClockPicker,
  ClockPickerProps,
  ClockPickerClasses,
  ClockPickerClassKey,
  clockPickerClasses,
  getClockPickerUtilityClass,
  CalendarPickerSkeleton,
  CalendarPickerSkeletonProps,
  CalendarPickerSkeletonClasses,
  CalendarPickerSkeletonClassKey,
  calendarPickerSkeletonClasses,
  getCalendarPickerSkeletonUtilityClass,
} from '@mui/x-date-pickers-pro';
