/* eslint-disable no-restricted-imports */
// @ts-nocheck
import {
  DateCalendar,
  DateCalendarProps,
  DateCalendarSlotsComponent,
  DateCalendarSlotsComponentsProps,
  DateCalendarClasses,
  DateCalendarClassKey,
  dateCalendarClasses,
  getDateCalendarUtilityClass,
  MonthCalendar,
  MonthCalendarProps,
  MonthCalendarClasses,
  MonthCalendarClassKey,
  monthCalendarClasses,
  getMonthCalendarUtilityClass,
  YearCalendar,
  YearCalendarProps,
  YearCalendarClasses,
  YearCalendarClassKey,
  yearCalendarClasses,
  getYearCalendarUtilityClass,
  TimeClock,
  TimeClockProps,
  TimeClockClasses,
  TimeClockClassKey,
  timeClockClasses,
  getTimeClockUtilityClass,
  DayCalendarSkeleton,
  DayCalendarSkeletonProps,
  DayCalendarSkeletonClasses,
  DayCalendarSkeletonClassKey,
  dayCalendarSkeletonClasses,
  getDayCalendarSkeletonUtilityClass,
} from '@mui/x-date-pickers-pro';
