export const OPERATOR_LABEL_MAPPING: { [key: string]: string } = {
  '=': 'equals',
  '!=': 'not equals',
  '>': 'is greater than',
  '>=': 'is greater than or equal to',
  '<': 'is less than',
  '<=': 'is less than or equal to',
};

export const OPERATOR_SYMBOL_MAPPING: { [key: string]: string } = {
  contains: '∋',
  equals: '=',
  '=': '=',
  '!=': '≠',
  '>': '>',
  '>=': '≥',
  '<': '<',
  '<=': '≤',
  startsWith: '⊃',
  endsWith: '⊂',
  is: '=',
  not: '≠',
  isNot: '≠',
  isEmpty: '∅',
  isNotEmpty: '∉',
  isIn: '∈',
  isNotIn: '∉',
  isLessThan: '<',
  isLessThanOrEqual: '≤',
  isGreaterThan: '>',
  isGreaterThanOrEqual: '≥',
  isBetween: '∈',
  isNotBetween: '∉',
  isAnyOf: '∈',
  after: '>',
  onOrAfter: '≥',
  before: '<',
  onOrBefore: '≤',
};
