name: Feature request 💄
description: Suggest a new idea for MUI X.
labels: ['status: waiting for maintainer']
body:
  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the issue in the title above ⬆️.

        Thanks for contributing by creating an issue! ❤️
  - type: input
    attributes:
      label: Search keywords
      description: Your issue may have already been reported! List the keywords you've used to search the [existing issues](https://github.com/mui/mui-x/issues). This will also make your issue searchable for others.
      placeholder: e.g. datagrid column resizing
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll bug fixes, performance enhancements, and other improvements into new releases.
      options:
        - label: I have tested the latest version
          required: true
  - type: textarea
    attributes:
      label: Summary
      description: Describe how it should work.
  - type: textarea
    attributes:
      label: Examples
      description: Provide a link to the Material Design specification, other implementations, or screenshots of the expected behavior.
  - type: textarea
    attributes:
      label: Motivation
      description: What are you trying to accomplish? How has the lack of this feature affected you? Providing context helps us come up with a solution that is more useful in the real world.
  - type: input
    id: contact
    attributes:
      label: Order ID or Support key 💳 (optional)
      description: The [Pro plan](https://mui.com/pricing/) comes with priority over the Community plan. Providing your order ID might give your problem more attention.
      placeholder: 'e.g. 11111'
