"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.gridTabIndexColumnGroupHeaderSelector = exports.gridTabIndexColumnHeaderFilterSelector = exports.gridTabIndexColumnHeaderSelector = exports.gridTabIndexCellSelector = exports.gridTabIndexStateSelector = exports.gridFocusColumnGroupHeaderSelector = exports.gridFocusColumnHeaderFilterSelector = exports.gridFocusColumnHeaderSelector = exports.gridFocusCellSelector = exports.gridFocusStateSelector = void 0;
var createSelector_1 = require("../../../utils/createSelector");
exports.gridFocusStateSelector = (0, createSelector_1.createRootSelector)(function (state) { return state.focus; });
exports.gridFocusCellSelector = (0, createSelector_1.createSelector)(exports.gridFocusStateSelector, function (focusState) { return focusState.cell; });
exports.gridFocusColumnHeaderSelector = (0, createSelector_1.createSelector)(exports.gridFocusStateSelector, function (focusState) { return focusState.columnHeader; });
exports.gridFocusColumnHeaderFilterSelector = (0, createSelector_1.createSelector)(exports.gridFocusStateSelector, function (focusState) { return focusState.columnHeaderFilter; });
exports.gridFocusColumnGroupHeaderSelector = (0, createSelector_1.createSelector)(exports.gridFocusStateSelector, function (focusState) { return focusState.columnGroupHeader; });
exports.gridTabIndexStateSelector = (0, createSelector_1.createRootSelector)(function (state) { return state.tabIndex; });
exports.gridTabIndexCellSelector = (0, createSelector_1.createSelector)(exports.gridTabIndexStateSelector, function (state) { return state.cell; });
exports.gridTabIndexColumnHeaderSelector = (0, createSelector_1.createSelector)(exports.gridTabIndexStateSelector, function (state) { return state.columnHeader; });
exports.gridTabIndexColumnHeaderFilterSelector = (0, createSelector_1.createSelector)(exports.gridTabIndexStateSelector, function (state) { return state.columnHeaderFilter; });
exports.gridTabIndexColumnGroupHeaderSelector = (0, createSelector_1.createSelector)(exports.gridTabIndexStateSelector, function (state) { return state.columnGroupHeader; });
