import * as React from 'react';
import Avatar from '@mui/material/Avatar';
import { GridRenderCellParams } from '@mui/x-data-grid-pro';

export function renderAvatar(params: GridRenderCellParams<string, { name: string }, any>) {
  if (params.rowNode.isAutoGenerated) {
    return '';
  }
  return (
    <Avatar style={{ backgroundColor: params.value }}>
      {params.row.name.toString().toUpperCase().substring(0, 1)}
    </Avatar>
  );
}
