export { FunnelChart as Unstable_FunnelChart } from './FunnelChart';
export type { FunnelChartProps, FunnelSeries } from './FunnelChart';
export * from './FunnelPlot';
export * from './funnel.types';
export * from './categoryAxis.types';
export * from './funnelSlots.types';
export type { FunnelCurveType } from './curves';
export { funnelSectionClasses } from './funnelSectionClasses';
export type { FunnelSectionClasses } from './funnelSectionClasses';
export { FunnelSection } from './FunnelSection';
export { FunnelSectionLabel } from './FunnelSectionLabel';
