import * as React from 'react';
import { ChatBoxThumb } from './components/thumbs/ChatBoxThumb';
import { ChatConversationThumb } from './components/thumbs/ChatConversationThumb';
import { ChatConversationListThumb, ChatMessageListThumb } from './components/thumbs/LayoutThumbs';
import {
  ChatConversationHeaderActionsThumb,
  ChatConversationHeaderInfoThumb,
  ChatConversationHeaderThumb,
  ChatConversationSubtitleThumb,
  ChatConversationTitleThumb,
} from './components/thumbs/HeaderThumbs';
import {
  ChatMessageActionsThumb,
  ChatMessageAuthorLabelThumb,
  ChatMessageAvatarThumb,
  ChatMessageContentThumb,
  ChatMessageErrorThumb,
  ChatMessageGroupThumb,
  ChatMessageInlineMetaThumb,
  ChatMessageMetaThumb,
  ChatMessageThumb,
} from './components/thumbs/MessageThumbs';
import {
  ChatComposerAttachButtonThumb,
  ChatComposerAttachmentListThumb,
  ChatComposerHelperTextThumb,
  ChatComposerLabelThumb,
  ChatComposerSendButtonThumb,
  ChatComposerTextAreaThumb,
  ChatComposerThumb,
  ChatComposerToolbarThumb,
} from './components/thumbs/ComposerThumbs';
import {
  ChatDateDividerThumb,
  ChatMessageSkeletonThumb,
  ChatScrollToBottomAffordanceThumb,
  ChatSuggestionsThumb,
  ChatTypingIndicatorThumb,
  ChatUnreadMarkerThumb,
} from './components/thumbs/StateThumbs';
import {
  ChatCodeBlockThumb,
  ChatConfirmationThumb,
  ChatMessageSourcesThumb,
} from './components/thumbs/AiThumbs';
import {
  ChatBoxPlayground,
  ChatCodeBlockPlayground,
  ChatComposerAttachButtonPlayground,
  ChatComposerAttachmentListPlayground,
  ChatComposerHelperTextPlayground,
  ChatComposerLabelPlayground,
  ChatComposerPlayground,
  ChatComposerSendButtonPlayground,
  ChatComposerTextAreaPlayground,
  ChatComposerToolbarPlayground,
  ChatConfirmationPlayground,
  ChatConversationHeaderActionsPlayground,
  ChatConversationHeaderInfoPlayground,
  ChatConversationHeaderPlayground,
  ChatConversationListPlayground,
  ChatConversationPlayground,
  ChatConversationSubtitlePlayground,
  ChatConversationTitlePlayground,
  ChatDateDividerPlayground,
  ChatMessageActionsPlayground,
  ChatMessageAuthorLabelPlayground,
  ChatMessageAvatarPlayground,
  ChatMessageContentPlayground,
  ChatMessageErrorPlayground,
  ChatMessageGroupPlayground,
  ChatMessageInlineMetaPlayground,
  ChatMessageListPlayground,
  ChatMessageMetaPlayground,
  ChatMessagePlayground,
  ChatMessageSkeletonPlayground,
  ChatMessageSourcesPlayground,
  ChatScrollToBottomAffordancePlayground,
  ChatSuggestionsPlayground,
  ChatTypingIndicatorPlayground,
  ChatUnreadMarkerPlayground,
} from './playgrounds';

export type GallerySectionId =
  | 'full-surfaces'
  | 'layout-and-navigation'
  | 'messages'
  | 'composer'
  | 'empty-loading-stream'
  | 'ai-rich-content';

export type GalleryEntryStatus = 'core' | 'compound' | 'slot' | 'state' | 'presentational';

export interface GalleryComponentEntry {
  id: string;
  title: string;
  importName: string;
  sectionId: GallerySectionId;
  sectionTitle: string;
  description: string;
  status: GalleryEntryStatus;
  parent?: string;
  slots?: string[];
  classKeys?: string[];
  docsPath?: string;
  sourcePath: string;
  playground: React.ReactNode;
  codeExample?: string;
  /** Optional inline-SVG schematic; falls back to PNG when omitted. */
  Thumbnail?: React.ComponentType;
}

export interface GallerySection {
  id: GallerySectionId;
  title: string;
  description: string;
  entries: GalleryComponentEntry[];
}

export interface GallerySearchItem {
  id: string;
  title: string;
  section: string;
  status: GalleryEntryStatus | 'section';
  description?: string;
  keywords: string[];
}

const sectionInfo: Array<Omit<GallerySection, 'entries'>> = [
  {
    id: 'full-surfaces',
    title: 'Full surfaces',
    description: 'Complete surfaces and high-level wrappers that compose the chat experience.',
  },
  {
    id: 'layout-and-navigation',
    title: 'Layout and navigation',
    description: 'Conversation chrome, headers, and the inbox-style conversation list.',
  },
  {
    id: 'messages',
    title: 'Messages',
    description: 'Message list, grouping, bubbles, metadata, actions, date boundaries, and errors.',
  },
  {
    id: 'composer',
    title: 'Composer',
    description:
      'The prompt form, textarea, attachment controls, toolbar, send button, and helper text.',
  },
  {
    id: 'empty-loading-stream',
    title: 'Empty, loading, and stream states',
    description: 'Suggestions, typing, unread markers, loading skeletons, and scroll affordances.',
  },
  {
    id: 'ai-rich-content',
    title: 'AI and rich content',
    description: 'Citations, code blocks, approval prompts, and presentational building blocks.',
  },
];

function entry(definition: Omit<GalleryComponentEntry, 'sectionTitle'>): GalleryComponentEntry {
  const section = sectionInfo.find((item) => item.id === definition.sectionId);
  if (!section) {
    throw new Error(`Unknown gallery section: ${definition.sectionId}`);
  }
  return { ...definition, sectionTitle: section.title };
}

export const galleryEntries: GalleryComponentEntry[] = [
  entry({
    id: 'chat-box',
    title: 'ChatBox',
    importName: 'ChatBox',
    sectionId: 'full-surfaces',
    status: 'core',
    description:
      'One-line full chat surface with layout, thread, messages, composer, and suggestions.',
    slots: [
      'conversationList',
      'conversationHeader',
      'messageList',
      'messageRoot',
      'messageContent',
      'composerRoot',
      'suggestions',
      'scrollToBottom',
    ],
    classKeys: ['root', 'layout', 'conversationsPane', 'threadPane'],
    docsPath: '/x/react-chat/basics/chat-box/',
    sourcePath: 'packages/x-chat/src/ChatBox/ChatBox.tsx',
    playground: <ChatBoxPlayground />,
    Thumbnail: ChatBoxThumb,
  }),
  entry({
    id: 'chat-conversation',
    title: 'ChatConversation',
    importName: 'ChatConversation',
    sectionId: 'full-surfaces',
    status: 'compound',
    description: 'Single thread shell that hosts the header, message list, and composer.',
    slots: ['root'],
    classKeys: ['root'],
    sourcePath: 'packages/x-chat/src/ChatConversation/ChatConversation.tsx',
    playground: <ChatConversationPlayground />,
    Thumbnail: ChatConversationThumb,
  }),
  entry({
    id: 'chat-conversation-list',
    title: 'ChatConversationList',
    importName: 'ChatConversationList',
    sectionId: 'layout-and-navigation',
    status: 'compound',
    description:
      'Inbox sidebar with row avatars, titles, previews, timestamps, actions, and unread badges.',
    slots: ['item', 'itemAvatar', 'itemContent', 'title', 'preview', 'timestamp', 'unreadBadge'],
    classKeys: ['root', 'item', 'itemSelected', 'itemUnread', 'itemFocused', 'compact'],
    sourcePath: 'packages/x-chat/src/ChatConversationList/ChatConversationList.tsx',
    playground: <ChatConversationListPlayground />,
    Thumbnail: ChatConversationListThumb,
  }),
  entry({
    id: 'chat-conversation-header',
    title: 'ChatConversationHeader',
    importName: 'ChatConversationHeader',
    sectionId: 'layout-and-navigation',
    status: 'compound',
    description: 'Top bar above a conversation with info and trailing actions.',
    slots: ['header'],
    classKeys: ['header'],
    sourcePath: 'packages/x-chat/src/ChatConversation/ChatConversationHeader.tsx',
    playground: <ChatConversationHeaderPlayground />,
    Thumbnail: ChatConversationHeaderThumb,
  }),
  entry({
    id: 'chat-conversation-header-info',
    title: 'ChatConversationHeaderInfo',
    importName: 'ChatConversationHeaderInfo',
    sectionId: 'layout-and-navigation',
    status: 'slot',
    parent: 'ChatConversationHeader',
    description: 'Info column that stacks the active conversation title and subtitle.',
    slots: ['headerInfo'],
    classKeys: ['headerInfo'],
    sourcePath: 'packages/x-chat/src/ChatConversation/ChatConversationHeaderInfo.tsx',
    playground: <ChatConversationHeaderInfoPlayground />,
    Thumbnail: ChatConversationHeaderInfoThumb,
  }),
  entry({
    id: 'chat-conversation-title',
    title: 'ChatConversationTitle',
    importName: 'ChatConversationTitle',
    sectionId: 'layout-and-navigation',
    status: 'slot',
    parent: 'ChatConversationHeaderInfo',
    description: 'Active conversation title read from chat context.',
    slots: ['title'],
    classKeys: ['title'],
    sourcePath: 'packages/x-chat/src/ChatConversation/ChatConversationTitle.tsx',
    playground: <ChatConversationTitlePlayground />,
    Thumbnail: ChatConversationTitleThumb,
  }),
  entry({
    id: 'chat-conversation-subtitle',
    title: 'ChatConversationSubtitle',
    importName: 'ChatConversationSubtitle',
    sectionId: 'layout-and-navigation',
    status: 'slot',
    parent: 'ChatConversationHeaderInfo',
    description: 'Secondary active conversation text, usually participants or status.',
    slots: ['subtitle'],
    classKeys: ['subtitle'],
    sourcePath: 'packages/x-chat/src/ChatConversation/ChatConversationSubtitle.tsx',
    playground: <ChatConversationSubtitlePlayground />,
    Thumbnail: ChatConversationSubtitleThumb,
  }),
  entry({
    id: 'chat-conversation-header-actions',
    title: 'ChatConversationHeaderActions',
    importName: 'ChatConversationHeaderActions',
    sectionId: 'layout-and-navigation',
    status: 'slot',
    parent: 'ChatConversationHeader',
    description: 'Trailing action container for search, more, pin, or custom controls.',
    slots: ['actions'],
    classKeys: ['headerActions'],
    sourcePath: 'packages/x-chat/src/ChatConversation/ChatConversationHeaderActions.tsx',
    playground: <ChatConversationHeaderActionsPlayground />,
    Thumbnail: ChatConversationHeaderActionsThumb,
  }),
  entry({
    id: 'chat-message-list',
    title: 'ChatMessageList',
    importName: 'ChatMessageList',
    sectionId: 'messages',
    status: 'compound',
    description: 'Scrollable message region with auto-scroll behavior and overlay affordances.',
    slots: ['messageList', 'messageListScroller', 'messageListContent', 'messageListOverlay'],
    classKeys: ['root', 'scroller', 'content'],
    sourcePath: 'packages/x-chat/src/ChatMessageList/ChatMessageList.tsx',
    playground: <ChatMessageListPlayground />,
    Thumbnail: ChatMessageListThumb,
  }),
  entry({
    id: 'chat-message-group',
    title: 'ChatMessageGroup',
    importName: 'ChatMessageGroup',
    sectionId: 'messages',
    status: 'compound',
    description: 'Groups consecutive messages from the same author into one visual cluster.',
    slots: ['group', 'authorName', 'groupTimestamp'],
    classKeys: ['group', 'groupAuthorName', 'groupTimestamp'],
    sourcePath: 'packages/x-chat/src/ChatMessage/ChatMessageGroup.tsx',
    playground: <ChatMessageGroupPlayground />,
    Thumbnail: ChatMessageGroupThumb,
  }),
  entry({
    id: 'chat-message',
    title: 'ChatMessage',
    importName: 'ChatMessage',
    sectionId: 'messages',
    status: 'compound',
    description:
      'Single message row that composes avatar, content, meta, actions, and error state.',
    slots: ['root'],
    classKeys: ['root', 'roleUser', 'roleAssistant', 'streaming', 'error'],
    sourcePath: 'packages/x-chat/src/ChatMessage/ChatMessage.tsx',
    playground: <ChatMessagePlayground />,
    Thumbnail: ChatMessageThumb,
  }),
  entry({
    id: 'chat-message-avatar',
    title: 'ChatMessageAvatar',
    importName: 'ChatMessageAvatar',
    sectionId: 'messages',
    status: 'slot',
    parent: 'ChatMessage',
    description: 'Author avatar slot with image and initials fallback.',
    slots: ['avatar', 'image'],
    classKeys: ['avatar'],
    sourcePath: 'packages/x-chat/src/ChatMessage/ChatMessageAvatar.tsx',
    playground: <ChatMessageAvatarPlayground />,
    Thumbnail: ChatMessageAvatarThumb,
  }),
  entry({
    id: 'chat-message-author-label',
    title: 'ChatMessageAuthorLabel',
    importName: 'ChatMessageAuthorLabel',
    sectionId: 'messages',
    status: 'slot',
    parent: 'ChatMessageGroup',
    description: 'Author name rendered above grouped messages.',
    slots: ['authorLabel'],
    classKeys: ['authorLabel'],
    sourcePath: 'packages/x-chat/src/ChatMessage/ChatMessageAuthorLabel.tsx',
    playground: <ChatMessageAuthorLabelPlayground />,
    Thumbnail: ChatMessageAuthorLabelThumb,
  }),
  entry({
    id: 'chat-message-content',
    title: 'ChatMessageContent',
    importName: 'ChatMessageContent',
    sectionId: 'messages',
    status: 'slot',
    parent: 'ChatMessage',
    description: 'Bubble content slot that renders text, markdown, code, and message parts.',
    slots: ['content', 'bubble'],
    classKeys: ['content', 'bubble'],
    sourcePath: 'packages/x-chat/src/ChatMessage/ChatMessageContent.tsx',
    playground: <ChatMessageContentPlayground />,
    Thumbnail: ChatMessageContentThumb,
  }),
  entry({
    id: 'chat-message-meta',
    title: 'ChatMessageMeta',
    importName: 'ChatMessageMeta',
    sectionId: 'messages',
    status: 'slot',
    parent: 'ChatMessage',
    description: 'External timestamp and delivery metadata used by compact message layouts.',
    slots: ['meta', 'timestamp', 'status', 'edited'],
    classKeys: ['meta'],
    sourcePath: 'packages/x-chat/src/ChatMessage/ChatMessageMeta.tsx',
    playground: <ChatMessageMetaPlayground />,
    Thumbnail: ChatMessageMetaThumb,
  }),
  entry({
    id: 'chat-message-inline-meta',
    title: 'ChatMessageInlineMeta',
    importName: 'ChatMessageInlineMeta',
    sectionId: 'messages',
    status: 'slot',
    parent: 'ChatMessageContent',
    description: 'Inline timestamp and delivery metadata that flows inside the bubble.',
    slots: ['inlineMeta', 'inlineMetaSpacer'],
    classKeys: ['inlineMeta', 'inlineMetaSpacer'],
    sourcePath: 'packages/x-chat/src/ChatMessage/ChatMessageInlineMeta.tsx',
    playground: <ChatMessageInlineMetaPlayground />,
    Thumbnail: ChatMessageInlineMetaThumb,
  }),
  entry({
    id: 'chat-message-actions',
    title: 'ChatMessageActions',
    importName: 'ChatMessageActions',
    sectionId: 'messages',
    status: 'slot',
    parent: 'ChatMessage',
    description: 'Hover or focus action toolbar for copy, regenerate, react, or custom actions.',
    slots: ['actions'],
    classKeys: ['actions'],
    sourcePath: 'packages/x-chat/src/ChatMessage/ChatMessageActions.tsx',
    playground: <ChatMessageActionsPlayground />,
    Thumbnail: ChatMessageActionsThumb,
  }),
  entry({
    id: 'chat-message-error',
    title: 'ChatMessageError',
    importName: 'ChatMessageError',
    sectionId: 'messages',
    status: 'state',
    parent: 'ChatMessage',
    description: 'Inline failed-message error with optional retry action.',
    classKeys: ['root', 'message', 'retryButton'],
    sourcePath: 'packages/x-chat/src/ChatMessageError/ChatMessageError.tsx',
    playground: <ChatMessageErrorPlayground />,
    Thumbnail: ChatMessageErrorThumb,
  }),
  entry({
    id: 'chat-date-divider',
    title: 'ChatDateDivider',
    importName: 'ChatDateDivider',
    sectionId: 'messages',
    status: 'state',
    parent: 'ChatMessageList',
    description: 'Day separator between message clusters.',
    classKeys: ['dateDivider'],
    sourcePath: 'packages/x-chat/src/ChatMessage/ChatDateDivider.tsx',
    playground: <ChatDateDividerPlayground />,
    Thumbnail: ChatDateDividerThumb,
  }),
  entry({
    id: 'chat-composer',
    title: 'ChatComposer',
    importName: 'ChatComposer',
    sectionId: 'composer',
    status: 'compound',
    description: 'Prompt form surface that hosts attachments, textarea, helper text, and toolbar.',
    slots: ['root'],
    classKeys: ['root', 'disabled', 'variantCompact'],
    sourcePath: 'packages/x-chat/src/ChatComposer/ChatComposer.tsx',
    playground: <ChatComposerPlayground />,
    Thumbnail: ChatComposerThumb,
  }),
  entry({
    id: 'chat-composer-text-area',
    title: 'ChatComposerTextArea',
    importName: 'ChatComposerTextArea',
    sectionId: 'composer',
    status: 'slot',
    parent: 'ChatComposer',
    description: 'Auto-growing textarea with Enter-to-submit behavior.',
    slots: ['input'],
    classKeys: ['textArea'],
    sourcePath: 'packages/x-chat/src/ChatComposer/ChatComposerTextArea.tsx',
    playground: <ChatComposerTextAreaPlayground />,
    Thumbnail: ChatComposerTextAreaThumb,
  }),
  entry({
    id: 'chat-composer-toolbar',
    title: 'ChatComposerToolbar',
    importName: 'ChatComposerToolbar',
    sectionId: 'composer',
    status: 'slot',
    parent: 'ChatComposer',
    description: 'Bottom row that hosts attach and send actions in the default composer.',
    slots: ['toolbar'],
    classKeys: ['toolbar'],
    sourcePath: 'packages/x-chat/src/ChatComposer/ChatComposerToolbar.tsx',
    playground: <ChatComposerToolbarPlayground />,
    Thumbnail: ChatComposerToolbarThumb,
  }),
  entry({
    id: 'chat-composer-send-button',
    title: 'ChatComposerSendButton',
    importName: 'ChatComposerSendButton',
    sectionId: 'composer',
    status: 'slot',
    parent: 'ChatComposerToolbar',
    description: 'Submit button that reads disabled and busy state from the composer store.',
    slots: ['sendButton'],
    classKeys: ['sendButton'],
    sourcePath: 'packages/x-chat/src/ChatComposer/ChatComposerSendButton.tsx',
    playground: <ChatComposerSendButtonPlayground />,
    Thumbnail: ChatComposerSendButtonThumb,
  }),
  entry({
    id: 'chat-composer-attach-button',
    title: 'ChatComposerAttachButton',
    importName: 'ChatComposerAttachButton',
    sectionId: 'composer',
    status: 'slot',
    parent: 'ChatComposerToolbar',
    description: 'File input trigger with attachment validation wiring.',
    slots: ['attachButton', 'attachInput'],
    classKeys: ['attachButton'],
    sourcePath: 'packages/x-chat/src/ChatComposer/ChatComposerAttachButton.tsx',
    playground: <ChatComposerAttachButtonPlayground />,
    Thumbnail: ChatComposerAttachButtonThumb,
  }),
  entry({
    id: 'chat-composer-attachment-list',
    title: 'ChatComposerAttachmentList',
    importName: 'ChatComposerAttachmentList',
    sectionId: 'composer',
    status: 'slot',
    parent: 'ChatComposer',
    description: 'Pending attachment chips rendered above the textarea.',
    slots: ['attachmentList'],
    classKeys: ['attachmentList'],
    sourcePath: 'packages/x-chat/src/ChatComposer/ChatComposerAttachmentList.tsx',
    playground: <ChatComposerAttachmentListPlayground />,
    Thumbnail: ChatComposerAttachmentListThumb,
  }),
  entry({
    id: 'chat-composer-helper-text',
    title: 'ChatComposerHelperText',
    importName: 'ChatComposerHelperText',
    sectionId: 'composer',
    status: 'slot',
    parent: 'ChatComposer',
    description: 'Caption or validation hint under the composer input.',
    slots: ['helperText'],
    classKeys: ['helperText'],
    sourcePath: 'packages/x-chat/src/ChatComposer/ChatComposerHelperText.tsx',
    playground: <ChatComposerHelperTextPlayground />,
    Thumbnail: ChatComposerHelperTextThumb,
  }),
  entry({
    id: 'chat-composer-label',
    title: 'ChatComposerLabel',
    importName: 'ChatComposerLabel',
    sectionId: 'composer',
    status: 'slot',
    parent: 'ChatComposer',
    description: 'Accessible label linked to the composer textarea.',
    slots: ['label'],
    classKeys: ['label'],
    sourcePath: 'packages/x-chat/src/ChatComposer/ChatComposerLabel.tsx',
    playground: <ChatComposerLabelPlayground />,
    Thumbnail: ChatComposerLabelThumb,
  }),
  entry({
    id: 'chat-suggestions',
    title: 'ChatSuggestions',
    importName: 'ChatSuggestions',
    sectionId: 'empty-loading-stream',
    status: 'state',
    parent: 'ChatMessageList',
    description: 'Prompt suggestions shown in an empty conversation.',
    slots: ['root', 'item'],
    classKeys: ['root', 'item'],
    sourcePath: 'packages/x-chat/src/ChatSuggestions/ChatSuggestions.tsx',
    playground: <ChatSuggestionsPlayground />,
    Thumbnail: ChatSuggestionsThumb,
  }),
  entry({
    id: 'chat-typing-indicator',
    title: 'ChatTypingIndicator',
    importName: 'ChatTypingIndicator',
    sectionId: 'empty-loading-stream',
    status: 'state',
    parent: 'ChatMessageList',
    description: 'Ambient typing signal for one or more participants.',
    slots: ['root'],
    classKeys: ['root', 'dot'],
    sourcePath: 'packages/x-chat/src/ChatIndicators/ChatTypingIndicator.tsx',
    playground: <ChatTypingIndicatorPlayground />,
    Thumbnail: ChatTypingIndicatorThumb,
  }),
  entry({
    id: 'chat-unread-marker',
    title: 'ChatUnreadMarker',
    importName: 'ChatUnreadMarker',
    sectionId: 'empty-loading-stream',
    status: 'state',
    parent: 'ChatMessageList',
    description: 'Boundary marker for the first unread message.',
    slots: ['root', 'label'],
    classKeys: ['root', 'label'],
    sourcePath: 'packages/x-chat/src/ChatIndicators/ChatUnreadMarker.tsx',
    playground: <ChatUnreadMarkerPlayground />,
    Thumbnail: ChatUnreadMarkerThumb,
  }),
  entry({
    id: 'chat-message-skeleton',
    title: 'ChatMessageSkeleton',
    importName: 'ChatMessageSkeleton',
    sectionId: 'empty-loading-stream',
    status: 'presentational',
    description: 'Animated placeholder for pending message content.',
    slots: ['root', 'line'],
    classKeys: ['root', 'line'],
    sourcePath: 'packages/x-chat/src/ChatMessageSkeleton/ChatMessageSkeleton.tsx',
    playground: <ChatMessageSkeletonPlayground />,
    Thumbnail: ChatMessageSkeletonThumb,
  }),
  entry({
    id: 'chat-scroll-to-bottom-affordance',
    title: 'ChatScrollToBottomAffordance',
    importName: 'ChatScrollToBottomAffordance',
    sectionId: 'empty-loading-stream',
    status: 'state',
    parent: 'ChatMessageList',
    description: 'Floating jump-to-latest affordance when the reader scrolls away from the bottom.',
    slots: ['root', 'badge', 'icon'],
    classKeys: ['root', 'badge', 'icon'],
    sourcePath: 'packages/x-chat/src/ChatIndicators/ChatScrollToBottomAffordance.tsx',
    playground: <ChatScrollToBottomAffordancePlayground />,
    Thumbnail: ChatScrollToBottomAffordanceThumb,
  }),
  entry({
    id: 'chat-message-sources',
    title: 'ChatMessageSources',
    importName: 'ChatMessageSources',
    sectionId: 'ai-rich-content',
    status: 'presentational',
    description: 'Manual citation list for grounded assistant answers.',
    slots: ['root', 'label', 'list'],
    classKeys: ['root', 'label', 'list'],
    sourcePath: 'packages/x-chat/src/ChatMessageSources/ChatMessageSources.tsx',
    playground: <ChatMessageSourcesPlayground />,
    Thumbnail: ChatMessageSourcesThumb,
  }),
  entry({
    id: 'chat-code-block',
    title: 'ChatCodeBlock',
    importName: 'ChatCodeBlock',
    sectionId: 'ai-rich-content',
    status: 'presentational',
    description: 'Default fenced-code renderer used by markdown messages.',
    classKeys: ['root', 'header', 'languageLabel', 'copyButton', 'pre', 'code'],
    sourcePath: 'packages/x-chat/src/ChatCodeBlock/ChatCodeBlock.tsx',
    playground: <ChatCodeBlockPlayground />,
    Thumbnail: ChatCodeBlockThumb,
  }),
  entry({
    id: 'chat-confirmation',
    title: 'ChatConfirmation',
    importName: 'ChatConfirmation',
    sectionId: 'ai-rich-content',
    status: 'presentational',
    description: 'Human approval prompt for tool calls and destructive agent actions.',
    classKeys: ['root', 'icon', 'message', 'actions', 'confirmButton', 'cancelButton'],
    sourcePath: 'packages/x-chat/src/ChatConfirmation/ChatConfirmation.tsx',
    playground: <ChatConfirmationPlayground />,
    Thumbnail: ChatConfirmationThumb,
  }),
];

export const gallerySections: GallerySection[] = sectionInfo.map((section) => ({
  ...section,
  entries: galleryEntries.filter((entryItem) => entryItem.sectionId === section.id),
}));

export const gallerySearchItems: GallerySearchItem[] = [
  ...gallerySections.map((section) => ({
    id: section.id,
    title: section.title,
    section: 'Section',
    status: 'section' as const,
    description: section.description,
    keywords: section.entries.map((item) => item.title),
  })),
  ...galleryEntries.map((item) => ({
    id: item.id,
    title: item.title,
    section: item.sectionTitle,
    status: item.status,
    description: item.description,
    keywords: [
      item.importName,
      item.parent,
      item.sourcePath,
      ...(item.slots ?? []),
      ...(item.classKeys ?? []),
    ].filter(Boolean) as string[],
  })),
];
