import * as React from 'react';
import MuiDivider from '@mui/material/Divider';
import { GridPreProcessor, useGridRegisterPreProcessor } from '@mui/x-data-grid/internals';
import { GridApiPro } from '../../../models/gridApiPro';
import { wrapColumnWithAggregation } from './gridAggregationUtils';
import { DataGridProProcessedProps } from '../../../models/dataGridProProps';
import { GridAggregationColumnMenuItems } from '../../../components/GridAggregationColumnMenuItems';

const Divider = () => <MuiDivider onClick={(event) => event.stopPropagation()} />;

export const useGridAggregationPreProcessors = (
  apiRef: React.MutableRefObject<GridApiPro>,
  props: Pick<DataGridProProcessedProps, 'aggregationFunctions' | 'aggregationPosition'>,
) => {
  const aggregationPositionRef = React.useRef(props.aggregationPosition);
  aggregationPositionRef.current = props.aggregationPosition;

  const updateGroupingColumn = React.useCallback<GridPreProcessor<'hydrateColumns'>>(
    (columnsState) => {
      columnsState.all.forEach((field) => {
        const colDef = columnsState.lookup[field];

        wrapColumnWithAggregation({
          colDef,
          apiRef,
          aggregationFunctions: props.aggregationFunctions,
          aggregationPositionRef,
        });
      });

      return columnsState;
    },
    [apiRef, props.aggregationFunctions, aggregationPositionRef],
  );

  const addGroupFooterRows = React.useCallback<GridPreProcessor<'hydrateRows'>>(
    (groupingParams) => {
      if (props.aggregationPosition === 'inline') {
        return groupingParams;
      }

      const ids = [...groupingParams.ids];
      const idRowsLookup = { ...groupingParams.idRowsLookup };
      const tree = { ...groupingParams.tree };

      groupingParams.ids.forEach((parentId) => {
        const node = tree[parentId];

        if (node.depth === groupingParams.treeDepth - 1) {
          return;
        }

        const footerId = `auto-generated-group-footer-${parentId}`;

        ids.push(footerId);
        idRowsLookup[footerId] = {};
        tree[footerId] = {
          id: footerId,
          isAutoGenerated: true,
          parent: parentId,
          depth: node.depth + 1,
          groupingKey: null,
          groupingField: null,
        };

        tree[parentId] = {
          ...tree[parentId],
          children: [...(tree[parentId].children ?? []), footerId],
        };
      });

      return {
        ...groupingParams,
        ids,
        idRowsLookup,
        tree,
      };
    },
    [props.aggregationPosition],
  );

  const addColumnMenuButtons = React.useCallback<GridPreProcessor<'columnMenu'>>(
    (initialValue, column) => {
      if (column.aggregable === false) {
        return initialValue;
      }

      return [...initialValue, <Divider />, <GridAggregationColumnMenuItems />];
    },
    [],
  );

  useGridRegisterPreProcessor(apiRef, 'hydrateColumns', updateGroupingColumn);
  useGridRegisterPreProcessor(apiRef, 'hydrateRows', addGroupFooterRows);
  useGridRegisterPreProcessor(apiRef, 'columnMenu', addColumnMenuButtons);
};
