import type { SchedulerEventId } from '@mui/x-scheduler-internals/models';
import type { SchedulerChangeEventDetails } from '@mui/x-scheduler-internals/internals';

export type SchedulerDependencyId = string | number;

export type SchedulerDependencyType =
  'FinishToStart' | 'StartToStart' | 'FinishToFinish' | 'StartToFinish';

export type SchedulerDependencyLagUnit = 'minute' | 'hour' | 'day';

/**
 * A dependency between two events, referencing them by id.
 */
export interface SchedulerDependency {
  /**
   * The unique identifier of the dependency.
   */
  id: SchedulerDependencyId;
  /**
   * The id of the predecessor event.
   */
  source: SchedulerEventId;
  /**
   * The id of the successor event.
   */
  target: SchedulerEventId;
  /**
   * The type of the dependency.
   * No type is enforced yet; the auto-scheduling engine will implement `"FinishToStart"` first.
   */
  type: SchedulerDependencyType;
  /**
   * The offset applied to the relationship, expressed in `lagUnit` units of elapsed (calendar) time.
   * Reserved for future use, not implemented yet.
   */
  lag?: number;
  /**
   * The unit of the `lag` offset.
   * Reserved for future use, not implemented yet.
   */
  lagUnit?: SchedulerDependencyLagUnit;
}

/**
 * Properties to create a dependency with `addDependency()`.
 * The id is generated by the store.
 */
export type SchedulerDependencyCreationProperties = Omit<SchedulerDependency, 'id'>;

export type SchedulerDependencyRejectionReason = 'recurringEvent' | 'unknownEvent';

export type SchedulerAddDependencyResult =
  | { status: 'added'; id: SchedulerDependencyId }
  | { status: 'rejected'; reason: SchedulerDependencyRejectionReason; eventId: SchedulerEventId };

/**
 * State slice holding the dependencies collection.
 */
export interface SchedulerDependenciesState {
  /**
   * The dependencies as provided to `props.dependencies`.
   */
  dependencyModelList: readonly SchedulerDependency[];
  /**
   * A lookup to get a dependency from its id.
   */
  dependencyModelLookup: Map<SchedulerDependencyId, SchedulerDependency>;
}

/**
 * Parameters to control the dependencies collection.
 */
export interface SchedulerDependenciesParameters {
  /**
   * The dependencies between events.
   * @default []
   */
  dependencies?: readonly SchedulerDependency[];
  /**
   * Event handler called when the dependencies change.
   */
  onDependenciesChange?: (
    value: SchedulerDependency[],
    eventDetails: SchedulerChangeEventDetails,
  ) => void;
}
