import type {
  SchedulerEventId,
  SchedulerEventSide,
  SchedulerResourceId,
} from '@mui/x-scheduler-internals/models';
import type { SchedulerChangeEventDetails } from '@mui/x-scheduler-internals/internals';

export type SchedulerDependencyId = string | number;

// Registers the dependencies as a selectable entity of the shared selection slice.
// Declared here (not in `typeOverloads`) so any program compiling the store also
// loads the augmentation.
declare module '@mui/x-scheduler-internals/models' {
  interface SchedulerSelectionTypeLookup {
    dependency: SchedulerDependencyId;
  }
}

/**
 * The PDM dependency types: which edge of the predecessor constrains which edge of
 * the successor.
 */
export type SchedulerDependencyType =
  'FinishToStart' | 'StartToStart' | 'FinishToFinish' | 'StartToFinish';

/**
 * The units a dependency lag can be expressed in.
 */
export type SchedulerDependencyLagUnit = 'minute' | 'hour' | 'day' | 'week';

/**
 * The lag of a dependency, normalized to the amount and unit the engine applies.
 */
export interface SchedulerDependencyLag {
  /**
   * How many `unit` the successor waits.
   */
  amount: number;
  /**
   * The unit `amount` is expressed in.
   */
  unit: SchedulerDependencyLagUnit;
}

/**
 * A dependency between two events, referencing them by id.
 * `source` is the predecessor and `target` the successor, whatever the type.
 */
export interface SchedulerDependency {
  /**
   * The unique identifier of the dependency.
   */
  id: SchedulerDependencyId;
  /**
   * The id of the event at the source end of the dependency.
   */
  source: SchedulerEventId;
  /**
   * The id of the event at the target end of the dependency.
   */
  target: SchedulerEventId;
  /**
   * The type of the dependency.
   */
  type: SchedulerDependencyType;
  /**
   * The calendar time the successor must wait after the constraining edge of the
   * predecessor, as a whole number of `lagUnit`, applied in the successor's timezone.
   * A value that is not a positive whole number, or an unknown `lagUnit` next to a lag,
   * discards the lag with a warning. Lead (a negative lag) is not supported yet, so the
   * same data will schedule differently once it is.
   * @default 0
   */
  lag?: number;
  /**
   * The unit of `lag`.
   * @default 'day'
   */
  lagUnit?: SchedulerDependencyLagUnit;
}

/**
 * Properties to create a dependency with `addDependency()`.
 * The id is generated by the store.
 */
export type SchedulerDependencyCreationProperties = Omit<SchedulerDependency, 'id'>;

/**
 * State of the pending create-dependency drag gesture, from a terminal to a target
 * event or one of its terminals.
 */
export interface SchedulerDependencyCreation {
  /**
   * The id of the event the gesture started from (the predecessor).
   */
  sourceEventId: SchedulerEventId;
  /**
   * The key of the occurrence the gesture started from.
   * Anchors the provisional arrow on the row appearance the user grabbed.
   */
  sourceOccurrenceKey: string;
  /**
   * The resource of the row appearance the gesture started from. The occurrence key
   * alone does not identify an appearance: an event assigned to several resources
   * repeats the same occurrence (and key) on each of its rows.
   */
  sourceResourceId: SchedulerResourceId;
  /**
   * The edge of the source event the gesture started from.
   */
  sourceSide: SchedulerEventSide;
  /**
   * The id of the event currently hovered as a valid drop target, if any.
   */
  targetEventId: SchedulerEventId | null;
  /**
   * The key of the hovered occurrence, so the provisional arrow snaps to the row
   * appearance under the pointer.
   */
  targetOccurrenceKey: string | null;
  /**
   * The resource of the hovered row appearance, qualifying `targetOccurrenceKey` the
   * same way `sourceResourceId` qualifies the source.
   */
  targetResourceId: SchedulerResourceId | null;
  /**
   * The edge of the hovered target the drop would land on: the hovered terminal's, or
   * the start edge on the event body. Together with `sourceSide`, it determines the
   * created dependency's type.
   */
  targetSide: SchedulerEventSide | null;
}

export type SchedulerDependencyEventRejectionReason =
  'recurringEvent' | 'unknownEvent' | 'readOnlyEvent';

export type SchedulerDependencyRejectionReason =
  SchedulerDependencyEventRejectionReason | 'duplicateDependency' | 'cyclicDependency';

export type SchedulerAddDependencyResult =
  | { status: 'added'; id: SchedulerDependencyId }
  | {
      status: 'rejected';
      reason: SchedulerDependencyEventRejectionReason;
      eventId: SchedulerEventId;
    }
  | { status: 'rejected'; reason: 'duplicateDependency'; dependencyId: SchedulerDependencyId }
  | { status: 'rejected'; reason: 'cyclicDependency' };

/**
 * State slice holding the dependencies collection.
 */
export interface SchedulerDependenciesState {
  /**
   * The dependencies as provided to `props.dependencies`.
   */
  dependencyModelList: readonly SchedulerDependency[];
  /**
   * A lookup to get a dependency from its id.
   */
  dependencyModelLookup: Map<SchedulerDependencyId, SchedulerDependency>;
}

/**
 * Parameters to control the dependencies collection.
 */
export interface SchedulerDependenciesParameters {
  /**
   * The dependencies between events. Providing a value — even an empty array —
   * enables the dependencies feature (terminals, arrows, selection); omitting it
   * disables the feature entirely.
   */
  dependencies?: readonly SchedulerDependency[];
  /**
   * Event handler called when the dependencies change.
   */
  onDependenciesChange?: (
    value: SchedulerDependency[],
    eventDetails: SchedulerChangeEventDetails,
  ) => void;
}
