// CSS_CLASSES_CONSTANTS
export const GRID_CSS_CLASS_PREFIX = 'MuiDataGrid';
export const GRID_ROOT_CSS_CLASS_SUFFIX = 'root';
export const GRID_COLUMN_HEADER_CSS_CLASS_SUFFIX = 'columnHeader';
export const GRID_ROW_CSS_CLASS_SUFFIX = 'row';
export const GRID_CELL_CSS_CLASS_SUFFIX = 'cell';

export const GRID_COLUMN_HEADER_CSS_CLASS = `${GRID_CSS_CLASS_PREFIX}-${GRID_COLUMN_HEADER_CSS_CLASS_SUFFIX}`;
export const GRID_ROW_CSS_CLASS = `${GRID_CSS_CLASS_PREFIX}-${GRID_ROW_CSS_CLASS_SUFFIX}`;
export const GRID_CELL_CSS_CLASS = `${GRID_CSS_CLASS_PREFIX}-${GRID_CELL_CSS_CLASS_SUFFIX}`;
export const GRID_COLUMN_HEADER_SEPARATOR_RESIZABLE_CSS_CLASS = `${GRID_CSS_CLASS_PREFIX}-columnSeparatorResizable`;
export const GRID_COLUMN_HEADER_TITLE_CSS_CLASS = `${GRID_CSS_CLASS_PREFIX}-columnHeaderTitleContainer`;
export const GRID_DATA_CONTAINER_CSS_CLASS = 'data-container';
export const GRID_COLUMN_HEADER_DROP_ZONE_CSS_CLASS = `${GRID_CSS_CLASS_PREFIX}-columnHeader-dropZone`;
export const GRID_COLUMN_HEADER_DRAGGING_CSS_CLASS = `${GRID_CSS_CLASS_PREFIX}-columnHeader-dragging`;
