import * as React from 'react';
import {
  GridFooterNode,
  GridGroupNode,
  GridRowId,
  GridRowIdGetter,
  GridRowModel,
  GridRowsLookup,
  GridRowTreeConfig,
  GridTreeNode,
} from '../../../models';
import { DataGridProcessedProps } from '../../../models/props/DataGridProps';
import { GridApiCommunity } from '../../../models/api/gridApiCommunity';
import {
  GridRowsFullUpdate,
  GridRowsInternalCache,
  GridRowsPartialUpdates,
  GridRowsState,
  GridRowTreeCreationParams,
} from './gridRowsInterfaces';

export const GRID_ROOT_GROUP_ID: GridRowId = `auto-generated-group-node-root`;

export const buildRootGroup = (): GridGroupNode => ({
  type: 'group',
  id: GRID_ROOT_GROUP_ID,
  depth: -1,
  groupingField: null,
  groupingKey: null,
  isAutoGenerated: true,
  children: [],
  childrenFromPath: {},
  childrenExpanded: true,
  parent: null,
});

/**
 * A helper function to check if the id provided is valid.
 * @param {GridRowId} id Id as [[GridRowId]].
 * @param {GridRowModel | Partial<GridRowModel>} row Row as [[GridRowModel]].
 * @param {string} detailErrorMessage A custom error message to display for invalid IDs
 */
export function checkGridRowIdIsValid(
  id: GridRowId,
  row: GridRowModel | Partial<GridRowModel>,
  detailErrorMessage: string = 'A row was provided without id in the rows prop:',
) {
  if (id == null) {
    throw new Error(
      [
        'MUI: The data grid component requires all rows to have a unique `id` property.',
        'Alternatively, you can use the `getRowId` prop to specify a custom id for each row.',
        detailErrorMessage,
        JSON.stringify(row),
      ].join('\n'),
    );
  }
}

export const getRowIdFromRowModel = (
  rowModel: GridRowModel,
  getRowId?: GridRowIdGetter,
  detailErrorMessage?: string,
): GridRowId => {
  const id = getRowId ? getRowId(rowModel) : rowModel.id;
  checkGridRowIdIsValid(id, rowModel, detailErrorMessage);
  return id;
};

export const getEmptyRowPartialUpdate = (): GridRowsPartialUpdates => ({
  type: 'partial',
  actions: {
    insert: [],
    modify: [],
    remove: [],
  },
  idToActionLookup: {},
});

export const createRowsInternalCache = ({
  rows,
  getRowId,
  loading,
}: Pick<DataGridProcessedProps, 'rows' | 'getRowId' | 'loading'>): GridRowsInternalCache => {
  const updates: GridRowsFullUpdate = {
    type: 'full',
    rows: [],
  };

  const dataRowIdToModelLookup: GridRowsLookup = {};
  const dataRowIdToIdLookup: Record<string, GridRowId> = {};

  for (let i = 0; i < rows.length; i += 1) {
    const model = rows[i];
    const id = getRowIdFromRowModel(model, getRowId);
    dataRowIdToModelLookup[id] = model;
    dataRowIdToIdLookup[id] = id;
    updates.rows.push(id);
  }

  return {
    rowsBeforePartialUpdates: rows,
    loadingPropBeforePartialUpdates: loading,
    updates,
    dataRowIdToIdLookup,
    dataRowIdToModelLookup,
  };
};

export const getRowsStateFromCache = ({
  apiRef,
  rowCountProp,
  loadingProp,
  previousTree,
  previousTreeDepths,
}: Pick<GridRowTreeCreationParams, 'previousTree' | 'previousTreeDepths'> & {
  apiRef: React.MutableRefObject<GridApiCommunity>;
  rowCountProp: number | undefined;
  loadingProp: boolean | undefined;
}): GridRowsState => {
  const { rowsBeforePartialUpdates, ...cacheForGrouping } = apiRef.current.unstable_caches.rows;
  const rowCount = rowCountProp ?? 0;

  const groupingResponse = apiRef.current.unstable_applyStrategyProcessor('rowTreeCreation', {
    ...cacheForGrouping,
    previousTree,
    previousTreeDepths,
  });

  const processingResponse = apiRef.current.unstable_applyPipeProcessors(
    'hydrateRows',
    groupingResponse,
  );

  const rootGroupNode = processingResponse.tree[GRID_ROOT_GROUP_ID] as GridGroupNode;
  const datasetSize = groupingResponse.dataRowIds.length;
  const dataTopLevelRowCount =
    rootGroupNode.children.length + (rootGroupNode.footerId == null ? 0 : 1);

  apiRef.current.unstable_caches.rows = {
    ...apiRef.current.unstable_caches.rows,
    updates: getEmptyRowPartialUpdate(),
  };

  return {
    groupingName: groupingResponse.groupingName,
    dataRowIds: groupingResponse.dataRowIds,
    tree: processingResponse.tree,
    treeDepths: processingResponse.treeDepths,
    loading: loadingProp,
    totalRowCount: Math.max(rowCount, datasetSize),
    totalTopLevelRowCount: Math.max(rowCount, dataTopLevelRowCount),
    dataRowIdToIdLookup: cacheForGrouping.dataRowIdToIdLookup,
    dataRowIdToModelLookup: cacheForGrouping.dataRowIdToModelLookup,
  };
};

export const getTreeNodeDescendants = (
  tree: GridRowTreeConfig,
  parentId: GridRowId,
  skipAutoGeneratedRows: boolean,
) => {
  const node = tree[parentId];
  if (node.type !== 'group') {
    return [];
  }

  const validDescendants: GridRowId[] = [];
  for (let i = 0; i < node.children.length; i += 1) {
    const child = node.children[i];
    const childNode = tree[child];
    if (
      !skipAutoGeneratedRows ||
      childNode.type === 'leaf' ||
      (childNode.type === 'group' && !childNode.isAutoGenerated)
    ) {
      validDescendants.push(child);
    }
    validDescendants.push(...getTreeNodeDescendants(tree, childNode.id, skipAutoGeneratedRows));
  }

  if (!skipAutoGeneratedRows && node.footerId != null) {
    validDescendants.push(node.footerId);
  }

  return validDescendants;
};

export const isAutoGeneratedRow = (
  rowNode: GridTreeNode,
): rowNode is GridGroupNode | GridFooterNode =>
  rowNode.type === 'footer' || (rowNode.type === 'group' && rowNode.isAutoGenerated);
