import {
  rainbowSurgePalette,
  blueberryTwilightPalette,
  mangoFusionPalette,
  cheerfulFiestaPalette,
  strawberrySkyPalette,
  signalDuoPalette,
  desertDunePalette,
  tropicalPunchPalette,
  sageGardenPalette,
  neonCyberPalette,
  autumnSpicePalette,
  sunsetCoralPalette,
  candyPopPalette,
  bluePalette,
  greenPalette,
  purplePalette,
  redPalette,
  orangePalette,
  yellowPalette,
  cyanPalette,
  pinkPalette,
  type ChartsColorPaletteCallback,
} from '@mui/x-charts/colorPalettes';

export const colorPaletteLookup: Map<string, ChartsColorPaletteCallback> = new Map([
  ['rainbowSurgePalette', rainbowSurgePalette],
  ['blueberryTwilightPalette', blueberryTwilightPalette],
  ['mangoFusionPalette', mangoFusionPalette],
  ['cheerfulFiestaPalette', cheerfulFiestaPalette],
  ['strawberrySkyPalette', strawberrySkyPalette],
  ['signalDuoPalette', signalDuoPalette],
  ['desertDunePalette', desertDunePalette],
  ['tropicalPunchPalette', tropicalPunchPalette],
  ['sageGardenPalette', sageGardenPalette],
  ['neonCyberPalette', neonCyberPalette],
  ['autumnSpicePalette', autumnSpicePalette],
  ['sunsetCoralPalette', sunsetCoralPalette],
  ['candyPopPalette', candyPopPalette],
  ['bluePalette', bluePalette],
  ['greenPalette', greenPalette],
  ['purplePalette', purplePalette],
  ['redPalette', redPalette],
  ['orangePalette', orangePalette],
  ['yellowPalette', yellowPalette],
  ['cyanPalette', cyanPalette],
  ['pinkPalette', pinkPalette],
]);
