"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.gridRowIdSelector = void 0;
var gridRowsUtils_1 = require("../features/rows/gridRowsUtils");
var createSelector_1 = require("../../utils/createSelector");
/**
 * Get the row id for a given row
 * @param apiRef - The grid api reference
 * @param {GridRowModel} row - The row to get the id for
 * @returns {GridRowId} The row id
 */
exports.gridRowIdSelector = (0, createSelector_1.createRootSelector)(function (state, row) {
    if (gridRowsUtils_1.GRID_ID_AUTOGENERATED in row) {
        return row[gridRowsUtils_1.GRID_ID_AUTOGENERATED];
    }
    return state.props.getRowId ? state.props.getRowId(row) : row.id;
});
