import { generateUtilityClasses } from './utils/material-ui-utils';

const rawClasses = [ 
  'root',
  'row',
  'row--editing',
  'cell',
  'withBorder',
  'cell--editing',
  'cell--editable',
  'cell--withRenderer',
  'cell--textLeft',
  'cell--textCenter',
  'cell--textRight',
  'columnHeader',
  'columnHeader--dragging',
  'columnHeaderWrapper',
  'scrollArea',
  'scrollArea--left',
  'scrollArea--right',
  'columnsContainer',
  'toolbarContainer',
  'overlay',
  'main',
  'dataContainer',
  'window',
  'windowContainer',
  'viewport',
  'autoHeight',
  'columnHeaderCheckbox',
  'cellCheckbox',
  'columnHeader--sorted',
  'columnHeader--sortable',
  'columnHeader--moving',
  'columnHeader--numeric',
  'columnHeader--alignLeft',
  'columnHeader--alignCenter',
  'columnHeader--alignRight',
  'columnHeaderDraggableContainer',
  'columnHeaderTitle',
  'iconButtonContainer',
  'sortIcon',
  'filterIcon',
  'menuIcon',
  'menuIconButton',
  'columnHeaderTitleContainer',
  'columnSeparator',
  'columnSeparator--resizable',
  'iconSeparator',
  'menuOpen',
  'editInputCell',
  'editBooleanCell',
  'booleanCell',
  'checkboxInput',
  'rowCount',
  'selectedRowCount',
  'footerContainer',
  'columnHeaderDropZone',
  'renderingZone'
] as const;

export type GridClassNames = Record<(typeof rawClasses)[number], string>;

export const gridClasses: GridClassNames = generateUtilityClasses('MuiDataGrid', [...rawClasses]);
