import { GridComponentProps } from './GridComponentProps';
import { useGridColumnMenu } from './hooks/features/columnMenu/useGridColumnMenu';
import { useGridColumnReorder } from './hooks/features/columnReorder/useGridColumnReorder';
import { useGridColumnResize } from './hooks/features/columnResize/useGridColumnResize';
import { useGridColumns } from './hooks/features/columns/useGridColumns';
import { useGridDensity } from './hooks/features/density/useGridDensity';
import { useGridCsvExport } from './hooks/features/export/useGridCsvExport';
import { useGridFilter } from './hooks/features/filter/useGridFilter';
import { useGridFocus } from './hooks/features/focus/useGridFocus';
import { useGridInfiniteLoader } from './hooks/features/infiniteLoader/useGridInfiniteLoader';
import { useGridKeyboard } from './hooks/features/keyboard/useGridKeyboard';
import { useGridKeyboardNavigation } from './hooks/features/keyboard/useGridKeyboardNavigation';
import { useLocaleText } from './hooks/features/localeText/useLocaleText';
import { useGridPagination } from './hooks/features/pagination/useGridPagination';
import { useGridPreferencesPanel } from './hooks/features/preferencesPanel/useGridPreferencesPanel';
import { useGridEditRows } from './hooks/features/rows/useGridEditRows';
import { useGridFreezeRows } from './hooks/features/rows/useGridFreezeRows';
import { useGridParamsApi } from './hooks/features/rows/useGridParamsApi';
import { useGridRows } from './hooks/features/rows/useGridRows';
import { useGridSelection } from './hooks/features/selection/useGridSelection';
import { useGridSorting } from './hooks/features/sorting/useGridSorting';
import { useGridComponents } from './hooks/features/useGridComponents';
import { useGridVirtualRows } from './hooks/features/virtualization/useGridVirtualRows';
import { useApi } from './hooks/root/useApi';
import { useEvents } from './hooks/root/useEvents';
import { useGridContainerProps } from './hooks/root/useGridContainerProps';
import { useErrorHandler } from './hooks/utils/useErrorHandler';
import { useGridScrollbarSizeDetector } from './hooks/utils/useGridScrollbarSizeDetector';
import { useLoggerFactory } from './hooks/utils/useLogger';
import { useOptionsProp } from './hooks/utils/useOptionsProp';
import { useRenderInfoLog } from './hooks/utils/useRenderInfoLog';
import { useResizeContainer } from './hooks/utils/useResizeContainer';
import { useStateProp } from './hooks/utils/useStateProp';
import { GridApiRef } from './models/api/gridApiRef';

export const useGridComponent = (apiRef: GridApiRef, props: GridComponentProps) => {
  useLoggerFactory(apiRef, props);
  useApi(apiRef);
  useErrorHandler(apiRef, props);
  useGridScrollbarSizeDetector(apiRef, props);
  useOptionsProp(apiRef, props);
  useEvents(apiRef);
  useLocaleText(apiRef);
  useResizeContainer(apiRef);
  useGridFreezeRows(apiRef, props);
  useGridColumns(apiRef, props);
  useGridParamsApi(apiRef);
  useGridRows(apiRef, props);
  useGridEditRows(apiRef);
  useGridFocus(apiRef);
  useGridKeyboard(apiRef);
  useGridKeyboardNavigation(apiRef);
  useGridSelection(apiRef);
  useGridSorting(apiRef, props);
  useGridColumnMenu(apiRef);
  useGridPreferencesPanel(apiRef);
  useGridFilter(apiRef, props);
  useGridContainerProps(apiRef);
  useGridDensity(apiRef);
  useGridVirtualRows(apiRef);
  useGridColumnReorder(apiRef);
  useGridColumnResize(apiRef);
  useGridPagination(apiRef);
  useGridCsvExport(apiRef);
  useGridInfiniteLoader(apiRef);
  useGridComponents(apiRef, props);
  useStateProp(apiRef, props);
  useRenderInfoLog(apiRef);
};
