name: Add reviewers to release PRs

on:
  # pull_request_target:
  #   branches: ['master', 'next']
  #   types: ['labeled']
  workflow_dispatch:

permissions: {}

jobs:
  add-reviewers-to-release-pr:
    uses: mui/mui-public/.github/workflows/reusable-add-a24bc8adf051b6b19ebdae8a80aaa2650d9b2ae7s-to-pr.yml@a24bc8adf051b6b19ebdae8a80aaa2650d9b2ae7-action
    with:
      team-slug: x
      label-name: release
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
