name: Add reviewers to release PRs

on:
  # pull_request_target:
  #   branches: ['master', 'next']
  #   types: ['labeled']
  workflow_dispatch:

permissions: {}

jobs:
  add-reviewers-to-release-pr:
    uses: mui/mui-public/.github/workflows/reusable-add-f709101a0ec2bf0f9de40196669863653bf0979fs-to-pr.yml@f709101a0ec2bf0f9de40196669863653bf0979f-action
    with:
      team-slug: x
      label-name: release
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
