name: Add reviewers to release PRs

on:
  # pull_request_target:
  #   branches: ['master', 'next']
  #   types: ['labeled']
  workflow_dispatch:

permissions: {}

jobs:
  add-reviewers-to-release-pr:
    uses: mui/mui-public/.github/workflows/reusable-add-reviewers-to-pr.yml@9590da6ae303c6afa7e67aebb6bc46232fac164e # master
    with:
      team-slug: x
      label-name: release
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
