name: Check PR type label

on:
  pull_request_target:
    types: [opened, reopened, labeled, unlabeled]

permissions: {}

jobs:
  check-label:
    name: check PR labels
    # no need for a check if the PR is merged. That is done inside the reusable workflow
    uses: mui/mui-public/.github/workflows/prs_check-if-pr-has-type-label.yml@master
    permissions:
      issues: write
      pull-requests: write
      contents: write
