name: CI

on:
  push:
    branches-ignore:
      # Renovate branches are always Pull Requests.
      # We don't need to run CI twice (push+pull_request)
      - 'renovate/**'
  pull_request:

permissions: {}

jobs:
  continuous-releases:
    name: Continuous releases
    if: ${{ github.repository_owner == 'mui' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }}"
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          # fetch all tags which are required for `pnpm release:changelog`
          fetch-depth: 0
      - name: Set up pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '22.23.1'
          # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm release:build
      - name: Publish packages to pkg.pr.new and npm dry-run
        uses: mui/mui-public/.github/actions/ci-publish@9590da6ae303c6afa7e67aebb6bc46232fac164e # master
        with:
          npm-dry-run: true
