name: Add closing message to issue

on:
  issues:
    types:
      - closed

permissions: {}

jobs:
  add-comment:
    name: Add closing message
    if: github.event.issue.state_reason == 'completed'
    uses: mui/mui-public/.github/workflows/issues_add-closing-message.yml@5a40e5ed0fc8d5ff358463279c75f69b33062d9f # master
    permissions:
      contents: read
      issues: write
