name: Add closing message to issue

on:
  issues:
    types:
      - closed

permissions: {}

jobs:
  add-comment:
    name: Add closing message
    if: github.event.issue.state_reason == 'completed'
    uses: mui/mui-public/.github/workflows/issues_add-closing-message.yml@fdfa28912aa56f2473702b4a49a5a7a3164f5e4c # master
    permissions:
      contents: read
      issues: write
