name: Add closing message to issue

on:
  issues:
    types:
      - closed

permissions: {}

jobs:
  add-comment:
    name: Add closing message
    if: github.event.issue.state_reason == 'completed'
    uses: mui/mui-public/.github/workflows/issues_add-closing-message.yml@c2ed9f97b6ea98e50de89d38b6cbc84c570316d9 # master
    permissions:
      contents: read
      issues: write
