name: No response

on:
  workflow_dispatch:
  schedule:
    # These runs in our repos are spread evenly throughout the day to avoid hitting rate limits.
    # If you change this schedule, consider changing the remaining repositories as well.
    # Runs at 3 am, 3 pm
    - cron: '0 3,15 * * *'

permissions: {}

jobs:
  noResponse:
    permissions:
      issues: write
      pull-requests: write
    name: Handle stale issues and PRs
    uses: mui/mui-public/.github/workflows/general_handle-stale-issues-and-prs.yml@dd7db35e4c70c656b86a98cf9b4819e7a4105f48 # master
