import { defineConfig } from 'rolldown/config';

export default defineConfig({
  input: [
    'src/BarChart/index.ts',
    'src/BarChartPro/index.ts',
    'src/ChartContainer/index.ts',
    'src/ChartContainerPro/index.ts',
    'src/ChartDataProvider/index.ts',
    'src/ChartDataProviderPro/index.ts',
    'src/ChartsAxis/index.ts',
    'src/ChartsAxisHighlight/index.ts',
    'src/ChartsBrushOverlay/index.ts',
    'src/ChartsClipPath/index.ts',
    'src/ChartsGrid/index.ts',
    'src/ChartsLabel/index.ts',
    'src/ChartsLegend/index.ts',
    'src/ChartsLocalizationProvider/index.ts',
    'src/ChartsOverlay/index.ts',
    'src/ChartsReferenceLine/index.ts',
    'src/ChartsSurface/index.ts',
    'src/ChartsText/index.ts',
    'src/ChartsToolbarPro/index.ts',
    'src/ChartsTooltip/index.ts',
    'src/ChartsWrapper/index.ts',
    'src/ChartsXAxis/index.ts',
    'src/ChartsYAxis/index.ts',
    'src/ChartZoomSlider/index.ts',
    'src/colorPalettes/index.ts',
    'src/constants/index.ts',
    'src/context/index.ts',
    'src/FunnelChart/index.ts',
    'src/Gauge/index.ts',
    'src/Heatmap/index.ts',
    'src/hooks/index.ts',
    'src/index.ts',
    'src/LineChart/index.ts',
    'src/LineChartPro/index.ts',
    'src/locales/index.ts',
    'src/models/index.ts',
    'src/PieChart/index.ts',
    'src/PieChartPro/index.ts',
    'src/plugins/index.ts',
    'src/RadarChart/index.ts',
    'src/RadarChartPro/index.ts',
    'src/SankeyChart/index.ts',
    'src/ScatterChart/index.ts',
    'src/ScatterChartPro/index.ts',
    'src/SparkLineChart/index.ts',
    'src/themeAugmentation/index.ts',
    'src/Toolbar/index.ts',
    'src/typeOverloads/index.ts',
  ],
  external: [
    /node_modules/,
    'react',
    'react-dom',
    'clsx',
    'prop-types',
    /^@babel/,
    /^@mui/,
    /^@emotion/,
  ],
  output: {
    preserveModules: true,
    preserveModulesRoot: 'src',
    dir: 'build',
    format: 'esm',
    minify: 'dce-only',
  },
});
